layout_spectrum: 0.7014344838327995
typography_spectrum: 0.4153657072914377
color:
  brandColors:
    - '#96CA2D'
    - '#B5E655'
    - '#EDF7F2'
    - '#4BB5C1'
    - '#7FC6BC'
  brandStrength: 0.12665270444466778
  lightness: 0.7632309891476231
  saturation: 0.8372806932419391
  rhythmicContrast: 0.346680954482849
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: robotic faces
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="http://polit.ru/media/photolib/2013/04/24/ps_kolmogorov_1_1366803032.jpg">
    src: 'http://polit.ru/media/photolib/2013/04/24/ps_kolmogorov_1_1366803032.jpg'
    metadata:
      author: []
      related: []
      publisher:
        url: 'http://polit.ru'
        name: Polit
        favicon: 'http://polit.ru/favicon.ico'
        domain: polit.ru
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      isBasedOnUrl: 'http://polit.ru/media/photolib/2013/04/24/ps_kolmogorov_1_1366803032.jpg'
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
title: roBOTic faces
description: >-
  My name is Denis. This a place where I describe my path in the world of math,
  AI and robotics
url: 'http://roboticfaces.engineer'
github: true
author:
  name: Denis Ambatenne
  email: dambatenne@gmail.com
analytics:
  google: UA-100379804-1
purpose:
  - type: external
    url: 'http://www.linkedin.com/in/ambatenne'
    label: LinkedIn
  - type: external
    url: 'https://github.com/dambatenne'
    label: GitHub
